version: '3'

services:
  bfaut:
    container_name: bfaut
    build:
      context: .
    image: dceoy/bfaut:latest
    restart: always
    environment:
      BFAUT_YML: /host/bfaut.yml
    volumes:
      - ${HOME}:/host
    working_dir: /host
    command:
      - auto
